services:

  postgres:
    image: postgres:18.6

    environment:
      POSTGRES_DB: pokemon_collection
      POSTGRES_USER: pokemon_app
      POSTGRES_PASSWORD: pokemon_dev_password

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U pokemon_app -d pokemon_collection"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s


  backend:
    build:
      context: ./backend
      dockerfile: Pokemon.Api/Dockerfile

    environment:
      ASPNETCORE_ENVIRONMENT: Production

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=pokemon_collection;Username=pokemon_app;Password=pokemon_dev_password"

      Jwt__Issuer: "Pokemon.Api"
      Jwt__Audience: "Pokemon.Frontend"
      Jwt__Key: "+SPG5c7p/xmXq7lTpOkGKxwvJbuJhK8DxCqWf0tC3RI="
      Jwt__ExpirationMinutes: "60"

      SeedDemoData: "true"

    depends_on:
      postgres:
        condition: service_healthy

    expose:
      - "8080"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "8080:80"

    depends_on:
      - backend


volumes:
  postgres_data: